### ISSUE TITLE
Doesn't seem to work with Rails 5 & Devise 4.2

### ISSUE THREAD

**Issue by lesliev** [bitzesty/devise_zxcvbn#20] opened 2016-08-03 09:40 UTC
This doesn't seem to work for Rails 5.0.0 and Devise 4.2.0 - it looks as if the code isn't called at all. I've not had time to dig into it, I just bypassed the problem with my own validation, similar to this: https://github.com/plataformatec/devise/wiki/How-To:-Set-up-simple-password-complexity-requirements.

**Comment by matthewford** [comment] 2016-08-03 17:03
@lesliev Thanks for reporting this, we'll have a look to see what is the issue.

**Comment by l0010o0001l** [comment] 2016-09-22 18:44
Hi @lesliev, 

Curious, is it the combination of Rails 5 & Devise 4.2 that renders incompatibility? Have you checked if it is incompatible with one or the other? (Rails 5 _only_ or Devise 4.2 _only)

**Comment by obduk** [comment] 2016-11-12 06:33
This might not be a Rails 5 specific issue, try downgrading to 2.1.1. See https://github.com/bitzesty/devise_zxcvbn/issues/24

**Comment by IlkhamGaysin** [comment] 2017-03-29 11:26
@lesliev 
I've tested with these gems and it works. Probably you had the different version of `devise_zxcvbn` could you provide whet was the version at the time of testing?
![test devise_zxcvbn](http://screenshots-ilkham.s3.eu-central-1.amazonaws.com/Fixing__2017-03-29_14-24-09.png)

```
rails (5.0.0)
devise (= 4.2.0)
devise_zxcvbn (4.4.1)
```

**Comment by IlkhamGaysin** [comment] 2017-03-29 11:49
I guess it's not related to rails 5.0.0 because in this version there are not any changes in `Active Model::Validations` that might skip the validation of this gem. Probably you skipped all validations by saving an object via `save(validate: false)` @lesliev

**Comment by IlkhamGaysin** [comment] 2017-03-29 11:51
Could you provide what exactly version of rails you had? @lesliev

**Comment by dreamfall** [comment] 2017-03-29 15:00
@lesliev 

I've tested on a new project with rails 5.0.2, devise 4.2.0 and devise_zxcvbn 4.4.1. devise_zxcvbn works as expected and displays validation error about the weak password score.
 
Closing this for now unless you provide a sample application that reproduces the error.

**Closed by dreamfall** 2017-03-29 15:00 UTC

**Comment by lesliev** [comment] 2017-03-29 20:30
Thanks for looking at this everyone, for some reason I missed all the emails. I was using 5.0.0 at the time but I've moved versions since then and made a lot of changes so it would be fairly impossible to get back to the state I was in. Best to close this, as you did!
